// <auto-generated />
using System;
using Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations.Structure
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240317162244_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DestinationsPhoto", b =>
                {
                    b.Property<int>("DestinationsId")
                        .HasColumnType("int")
                        .HasColumnName("destinations_id");

                    b.Property<int>("PhotosId")
                        .HasColumnType("int")
                        .HasColumnName("photos_id");

                    b.HasKey("DestinationsId", "PhotosId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PhotosId" }, "photos_id");

                    b.ToTable("destinations_photos", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("country");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("street");

                    b.Property<string>("Street2")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("street2");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Admin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_edit");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Address")
                        .HasColumnType("int")
                        .HasColumnName("address");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Address" }, "address");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Address")
                        .HasColumnType("int")
                        .HasColumnName("address");

                    b.Property<bool>("Availible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("availible");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Address" }, "address")
                        .HasDatabaseName("address1");

                    b.ToTable("destinations", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Employee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Branch")
                        .HasColumnType("int")
                        .HasColumnName("branch");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Branch" }, "branch");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Order", b =>
                {
                    b.Property<int>("PackageSchedules")
                        .HasColumnType("int")
                        .HasColumnName("package_schedules");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<bool>("HasBeenPaid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_been_paid");

                    b.HasKey("PackageSchedules", "UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "userId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool?>("Availible")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("availible")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Room")
                        .HasColumnType("int")
                        .HasColumnName("room");

                    b.Property<int?>("RootPackageId")
                        .HasColumnType("int")
                        .HasColumnName("root_package_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedBy" }, "created_by");

                    b.HasIndex(new[] { "Room" }, "room");

                    b.HasIndex(new[] { "RootPackageId" }, "root_package_id");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.PackageSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("date")
                        .HasColumnName("date_start");

                    b.Property<short>("Days")
                        .HasColumnType("smallint")
                        .HasColumnName("days");

                    b.Property<int>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("package_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PackageId" }, "package_id");

                    b.ToTable("package_schedules", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<byte[]>("Photo1")
                        .IsRequired()
                        .HasColumnType("blob")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("AmountAvailible")
                        .HasColumnType("int")
                        .HasColumnName("amount_availible");

                    b.Property<bool?>("Availible")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("availible")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Beds")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("beds");

                    b.Property<decimal>("CostPerNight")
                        .HasPrecision(15)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("cost_per_night");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Destination")
                        .HasColumnType("int")
                        .HasColumnName("destination");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Destination" }, "destination");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Decription")
                        .HasColumnType("text")
                        .HasColumnName("decription");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Addresses")
                        .HasColumnType("int")
                        .HasColumnName("addresses");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNum")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone_num");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Addresses" }, "addresses");

                    b.HasIndex(new[] { "Email" }, "users_index_0");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RoomsPhoto", b =>
                {
                    b.Property<int>("RoomsId")
                        .HasColumnType("int")
                        .HasColumnName("rooms_id");

                    b.Property<int>("PhotosId")
                        .HasColumnType("int")
                        .HasColumnName("photos_id");

                    b.HasKey("RoomsId", "PhotosId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PhotosId" }, "photos_id")
                        .HasDatabaseName("photos_id1");

                    b.ToTable("rooms_photos", (string)null);
                });

            modelBuilder.Entity("TagsDestination", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int")
                        .HasColumnName("tags_id");

                    b.Property<int>("DestinationsId")
                        .HasColumnType("int")
                        .HasColumnName("destinations_id");

                    b.HasKey("TagsId", "DestinationsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DestinationsId" }, "destinations_id");

                    b.ToTable("tags_destinations", (string)null);
                });

            modelBuilder.Entity("TagsPackage", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int")
                        .HasColumnName("tags_id");

                    b.Property<int>("PackagesId")
                        .HasColumnType("int")
                        .HasColumnName("packages_id");

                    b.HasKey("TagsId", "PackagesId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PackagesId" }, "packages_id");

                    b.ToTable("tags_packages", (string)null);
                });

            modelBuilder.Entity("TagsRoom", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int")
                        .HasColumnName("tags_id");

                    b.Property<int>("RoomsId")
                        .HasColumnType("int")
                        .HasColumnName("rooms_id");

                    b.HasKey("TagsId", "RoomsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoomsId" }, "rooms_id");

                    b.ToTable("tags_rooms", (string)null);
                });

            modelBuilder.Entity("DestinationsPhoto", b =>
                {
                    b.HasOne("Domain.Entity.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationsId")
                        .IsRequired()
                        .HasConstraintName("destinations_photos_ibfk_1");

                    b.HasOne("Domain.Entity.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotosId")
                        .IsRequired()
                        .HasConstraintName("destinations_photos_ibfk_2");
                });

            modelBuilder.Entity("Domain.Entity.Admin", b =>
                {
                    b.HasOne("Domain.Entity.Employee", "IdNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("Domain.Entity.Admin", "Id")
                        .IsRequired()
                        .HasConstraintName("admin_ibfk_1");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Domain.Entity.Branch", b =>
                {
                    b.HasOne("Domain.Entity.Address", "AddressNavigation")
                        .WithMany("Branches")
                        .HasForeignKey("Address")
                        .HasConstraintName("branches_ibfk_1");

                    b.Navigation("AddressNavigation");
                });

            modelBuilder.Entity("Domain.Entity.Destination", b =>
                {
                    b.HasOne("Domain.Entity.Address", "AddressNavigation")
                        .WithMany("Destinations")
                        .HasForeignKey("Address")
                        .IsRequired()
                        .HasConstraintName("destinations_ibfk_1");

                    b.Navigation("AddressNavigation");
                });

            modelBuilder.Entity("Domain.Entity.Employee", b =>
                {
                    b.HasOne("Domain.Entity.Branch", "BranchNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("Branch")
                        .HasConstraintName("employees_ibfk_2");

                    b.HasOne("Domain.Entity.User", "IdNavigation")
                        .WithOne("Employee")
                        .HasForeignKey("Domain.Entity.Employee", "Id")
                        .IsRequired()
                        .HasConstraintName("employees_ibfk_1");

                    b.Navigation("BranchNavigation");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Domain.Entity.Order", b =>
                {
                    b.HasOne("Domain.Entity.Package", "PackageSchedulesNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("PackageSchedules")
                        .IsRequired()
                        .HasConstraintName("orders_ibfk_1");

                    b.HasOne("Domain.Entity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("orders_ibfk_2");

                    b.Navigation("PackageSchedulesNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entity.Package", b =>
                {
                    b.HasOne("Domain.Entity.Admin", "CreatedByNavigation")
                        .WithMany("Packages")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("packages_ibfk_2");

                    b.HasOne("Domain.Entity.Room", "RoomNavigation")
                        .WithMany("Packages")
                        .HasForeignKey("Room")
                        .IsRequired()
                        .HasConstraintName("packages_ibfk_1");

                    b.HasOne("Domain.Entity.Package", "RootPackage")
                        .WithMany("InverseRootPackage")
                        .HasForeignKey("RootPackageId")
                        .HasConstraintName("packages_ibfk_3");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("RoomNavigation");

                    b.Navigation("RootPackage");
                });

            modelBuilder.Entity("Domain.Entity.PackageSchedule", b =>
                {
                    b.HasOne("Domain.Entity.Package", "Package")
                        .WithMany("PackageSchedules")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("package_schedules_ibfk_1");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Domain.Entity.Photo", b =>
                {
                    b.HasOne("Domain.Entity.Destination", "IdNavigation")
                        .WithOne("Photo")
                        .HasForeignKey("Domain.Entity.Photo", "Id")
                        .IsRequired()
                        .HasConstraintName("photos_ibfk_1");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Domain.Entity.Room", b =>
                {
                    b.HasOne("Domain.Entity.Destination", "DestinationNavigation")
                        .WithMany("Rooms")
                        .HasForeignKey("Destination")
                        .IsRequired()
                        .HasConstraintName("rooms_ibfk_1");

                    b.Navigation("DestinationNavigation");
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.HasOne("Domain.Entity.Address", "AddressesNavigation")
                        .WithMany("Users")
                        .HasForeignKey("Addresses")
                        .HasConstraintName("users_ibfk_1");

                    b.Navigation("AddressesNavigation");
                });

            modelBuilder.Entity("RoomsPhoto", b =>
                {
                    b.HasOne("Domain.Entity.Photo", null)
                        .WithMany()
                        .HasForeignKey("PhotosId")
                        .IsRequired()
                        .HasConstraintName("rooms_photos_ibfk_2");

                    b.HasOne("Domain.Entity.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .IsRequired()
                        .HasConstraintName("rooms_photos_ibfk_1");
                });

            modelBuilder.Entity("TagsDestination", b =>
                {
                    b.HasOne("Domain.Entity.Destination", null)
                        .WithMany()
                        .HasForeignKey("DestinationsId")
                        .IsRequired()
                        .HasConstraintName("tags_destinations_ibfk_2");

                    b.HasOne("Domain.Entity.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .IsRequired()
                        .HasConstraintName("tags_destinations_ibfk_1");
                });

            modelBuilder.Entity("TagsPackage", b =>
                {
                    b.HasOne("Domain.Entity.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesId")
                        .IsRequired()
                        .HasConstraintName("tags_packages_ibfk_2");

                    b.HasOne("Domain.Entity.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .IsRequired()
                        .HasConstraintName("tags_packages_ibfk_1");
                });

            modelBuilder.Entity("TagsRoom", b =>
                {
                    b.HasOne("Domain.Entity.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .IsRequired()
                        .HasConstraintName("tags_rooms_ibfk_2");

                    b.HasOne("Domain.Entity.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .IsRequired()
                        .HasConstraintName("tags_rooms_ibfk_1");
                });

            modelBuilder.Entity("Domain.Entity.Address", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Destinations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entity.Admin", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Domain.Entity.Branch", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entity.Destination", b =>
                {
                    b.Navigation("Photo");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Domain.Entity.Employee", b =>
                {
                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Domain.Entity.Package", b =>
                {
                    b.Navigation("InverseRootPackage");

                    b.Navigation("Orders");

                    b.Navigation("PackageSchedules");
                });

            modelBuilder.Entity("Domain.Entity.Room", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Domain.Entity.User", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
